### ISSUE TITLE
Some assembly tags not present in a loop section

### ISSUE THREAD

**Issue by jonwedell** [uwbmrb/smolscripts#1]
Hey Dimitri,

In the assembly saveframe of the output JSON data, the following three tags are at the saveframe level, but seem like they should be in a loop. Here is an excerpt from the assembly section of `lovastatin.json`:

```
{
      "sf_category": "assembly",
      "name": "assembly_1",
      ...
      "conformational_isomer": "no",
      "chemical_exchange_state": "no",
      "physical_state": "native",
}
```

but the three tags I've shown here are actually part of the assembly loop `_Entity_assembly`, so it seems it should be:

```
{
      "sf_category": "assembly",
      "name": "assembly_1",
      ...
      "entity_assembly": 
      [{
      "conformational_isomer": "no",
      "chemical_exchange_state": "no",
      "physical_state": "native",
      }]
}
```

Is this an easy fix or am I misinterpreting the JSON file? Thanks!

**Comment by dmaziuk** [comment]
yeah, looks like sloppy copy-pasing on my part ;)

**Comment by dmaziuk** [comment]
hmmm... I thought the above was supposed to close it
